openapi: 3.0.1
info:
  title: GetCountriesByISO
  description: API Definition of GetCountriesByISO
  version: 1.0.0
servers:
- url: http://localhost:8290/countryIso
paths:
  /{ISOCode}:
    get:
      parameters:
      - name: ISOCode
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
